[features]
seeds = false
[programs.localnet]
simple_anchor_dapp = "GZ2Tyz9Ny5hsunTuydpHHXNppY86cH5zNVBHFrwCJEyB"
[programs.devnet]
simple_anchor_dapp = "66aoA3njN9pM3WyaaVr3PcLViq6aZycPR3Pf4bz3qtCU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/irshad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
